# This is a basic workflow to help you get started with Actions

name: testInputs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # schedule:
  #  - cron: '30 16 * * 5'
  push:
  #  branches: [ beta ]
    branches-ignore: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Switch to branch beta
      - name: Switch to branch beta
        run: git checkout beta

      # Setup Miniconda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          auto-update-conda: true

      # Activate environment.yml and run test
      - name: Create env
        shell: bash -l {0}
        run: |
          conda env create -f environment.yml
          conda activate precogx
          pip install pytest
          python -m pytest --import-mode=append tests/
        

      # run the test.py to get the latest SIFT and PDB FASTA files
      #- name: execute test.py script
      #  run: python test.py

      # Install and run MAKEDB
      #- name: Install BLAST and run makeblastdb
      #  shell: bash -l {0}
      #  run: |
      #    conda install -c bioconda blast
      #    mkdir blastdb
      #    makeblastdb -in data/fasta/all_pdbs.fasta -dbtype 'prot' -out data/fasta/blastdb/all_pdbs

      # commit
      # - name: commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add -A
      #     git commit -m "update data" -a

      # # push
      # - name: push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main
